### ISSUE TITLE
When starting code recently after closing : error exec: code not found

### ISSUE THREAD

**Issue by rrichardson** [owtaylor/toolbox-vscode#8] opened 2021-06-02 16:19 UTC
Thanks for taking the time to thoroughly make Code in Toolbox a pleasant experience.  I've had no problems with the script other than this one: 

If I start code after closing it (which I sometimes do to reset an LSP, or I installed an extension that requires restart) 

I get this : 
```
/var/home/me/my-project-dir: line 3: exec: code: not found
```

If I wait 60 or so seconds,  not sure on the exact time,  then it works just fine.  
I haven't been able to trace the line of code that originates the error, it seems to come from nowhere :) 
I wonder if this is related to :  https://github.com/flathub/com.visualstudio.code/issues/210  
Where the script is finding the previous IPC channel that hasn't yet closed.   After the channel is cleaned up, then the script launches "from scratch" again.  Just a guess.

**Comment by Steve229** [comment] 2021-07-25 19:19
Same issue here... but waiting didn't help at all. I killed my terminal(s) and waited about 15 minutes - still got the error message. After logging out and back in again it worked fine.

But when it's working it's great - thanks for the effort to get this working!

**Comment by anthr76** [comment] 2021-09-11 03:02
https://github.com/owtaylor/toolbox-vscode/blob/273ea0e2e5873c8569519b46452fabb16c178bc0/code.sh#L385-L417

**Comment by owtaylor** [comment] 2021-11-05 14:53
I've merged a change that should help here - https://github.com/owtaylor/toolbox-vscode/pull/12 - if people could test that would be appreciated!

**Comment by anthr76** [comment] 2021-11-05 14:59
@owtaylor I just performed a quick test.. Executing `code .` a few times in different directories and I cannot reproduce this anymore! 🎉 

Incredibly nice work.

**Comment by owtaylor** [comment] 2021-11-05 16:20
> @owtaylor I just performed a quick test.. Executing `code .` a few times in different directories and I cannot reproduce this anymore! tada

Thanks for the testing!

**Closed by owtaylor** 2021-11-05 16:20 UTC
